// prisma/seed.ts
import { PrismaClient, UserRole, RsvpStatus } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  // Orlando center-ish
  const orlando = { lat: 28.5383, lng: -81.3792 }

  // Create a promoter user
  const promoter = await prisma.user.upsert({
    where: { email: "promoter@example.com" },
    update: { role: "PROMOTER" },
    create: {
      email: "promoter@example.com",
      name: "Blue Bar Promoter",
      role: UserRole.PROMOTER,
      profile: { create: {} }
    }
  })

  // Business
  const biz = await prisma.business.create({
    data: {
      ownerId: promoter.id,
      name: "Blue Bar",
      address: "Downtown Orlando, FL",
      lat: orlando.lat,
      lng: orlando.lng,
      verified: true
    }
  })

  const now = new Date()
  const tonight = new Date(now.getTime() + 6 * 60 * 60 * 1000)
  const threeHours = new Date(tonight.getTime() + 3 * 60 * 60 * 1000)

  // Seed a few events
  const categories = ["Bars", "Live Music", "Students", "Sports", "Religious", "Networking"]
  for (let i = 0; i < 6; i++) {
    const starts = new Date(tonight.getTime() + i * 60 * 60 * 1000)
    const ends = new Date(starts.getTime() + 3 * 60 * 60 * 1000)
    await prisma.event.create({
      data: {
        createdById: promoter.id,
        businessId: biz.id,
        title: `${categories[i]} Night #${i+1}`,
        category: categories[i],
        description: "Autogenerated seed event",
        address: "Miami, FL",
        lat: orlando.lat + (Math.random() - 0.5) * 0.08,
        lng: orlando.lng + (Math.random() - 0.5) * 0.08,
        startsAt: starts,
        endsAt: ends,
        is18Plus: i % 2 === 0,
        is21Plus: i % 3 === 0
      }
    })
  }

  // A seeker user with an RSVP
  const seeker = await prisma.user.upsert({
    where: { email: "seeker@example.com" },
    update: {},
    create: {
      email: "seeker@example.com",
      name: "Curious Seeker",
      profile: { create: { homeLat: orlando.lat, homeLng: orlando.lng } }
    }
  })

  const firstEvent = await prisma.event.findFirst()
  if (firstEvent) {
    await prisma.rSVP.upsert({
      where: { userId_eventId: { userId: seeker.id, eventId: firstEvent.id } },
      update: { status: RsvpStatus.GOING },
      create: { userId: seeker.id, eventId: firstEvent.id, status: RsvpStatus.GOING }
    })
  }

  // Update geom after seed
  await prisma.$executeRawUnsafe(`
    UPDATE "Event"
    SET geom = ST_SetSRID(ST_MakePoint("lng","lat"),4326)::geography
    WHERE geom IS NULL;
  `)

  console.log("Seed complete.")
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
}).finally(async () => {
  await prisma.$disconnect()
})
